server:
  port: 9010

spring:
  application:
    name: "message"
  profiles:
    active: git
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
        emailsms-out-0:
          destination: communication-sent
  rabbitmq:
    host: svc-rabbitmq-app
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s