---
apiVersion: v1
kind: Service
metadata:
  name: svc-message-app
  namespace: group1-team2
spec:
  selector:
    app: d-group1-team2-message
  ports:
    - protocol: TCP
      port: 8801
      targetPort: 8801
      nodePort: 30207
  type: NodePort